### ISSUE TITLE
Circadian service repeatedly fails to start - wrong executable location

### ISSUE THREAD

**Issue by IanPul** [mrmekon/circadian#24]
I just installed Circadian in Fedora38. After following the build / installations instruction here, I found that the service status was reported as failed:

May 25 17:16:54 ian-nas.local systemd[1]: circadian.service: Start request repeated too quickly.
May 25 17:16:54 ian-nas.local systemd[1]: circadian.service: Failed with result 'exit-code'.
May 25 17:16:54 ian-nas.local systemd[1]: Failed to start circadian.service - Circadian power management service.

Looking in the syslog I found that it was in a restart loop, constantly restarting until systemd's restart time limiting kicked in. Then I noticed this in there:

May 25 17:42:07 ian-nas.local audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=circadian comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=suc>
May 25 17:42:07 ian-nas.local audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=circadian comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=succ>
May 25 17:42:07 ian-nas.local (ircadian)[1783]: **circadian.service: Failed to locate executable /usr/bin/circadian: No such file or directory**

The problem is that the installation instruction here say **sudo cp target/release/circadian /usr/local/bin/**, but circadian.service contains **ExecStart=/usr/bin/circadian**. I edited that latter to /usr/local/bin, and now the service is running.

**Comment by mrmekon** [comment]
Thanks, I've updated the systemd service file now!
