### ISSUE TITLE
Unwanted shutdown when connected over ssh on zsh with putty

### ISSUE THREAD

**Issue by lemba23** [mrmekon/circadian#8]
Hi,
the script is shutting down my server even when I'm connected over ssh with putty on my zsh shell.

I appriciate your script and the way you implented it and I would be happy to help you with any further information you need.

**Comment by mrmekon** [comment]
I guess you have probably moved on, but you can use `pkill -SIGUSR1 circadian` to dump all of the variables Circadian is tracking to syslog and check why it isn't working.  For ssh, it checks for processes named "ssh" or "sshd".  If you run an ssh process with a different name, you'll need to update the regex in `exist_net_connection` and rebuild.
